// <auto-generated />
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(UserContext))]
    [Migration("20230130233525_seed")]
    partial class seed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Models.User", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text");

                    b.Property<bool>("Ban")
                        .HasColumnType("boolean");

                    b.Property<string>("BanReason")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            Ban = false,
                            Email = "admin@workspace.com",
                            Firstname = "Admin",
                            Lastname = "Admin",
                            Username = "admin@workspace.com"
                        },
                        new
                        {
                            ID = "2",
                            Ban = false,
                            Email = "kwiatkowski@workspace.com",
                            Firstname = "Jan",
                            Lastname = "Kwiatkowski",
                            Username = "kwiatkowski@workspace.com"
                        },
                        new
                        {
                            ID = "3",
                            Ban = false,
                            Email = "mila@workspace.com",
                            Firstname = "Anna",
                            Lastname = "Miła",
                            Username = "mila@workspace.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
